cmake_minimum_required(VERSION 3.21)

set(ENV{HOME} "/lvrs-test-home")
unset(ENV{LVRS_INSTALL_PREFIX})
set(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT TRUE)
include("${LVRS_SOURCE_DIR}/cmake/LVRSInstallDefaults.cmake")
if(NOT CMAKE_INSTALL_PREFIX STREQUAL "/lvrs-test-home/.local/SDK/LVRS")
    message(FATAL_ERROR "Default install prefix must be inside the SDK directory.")
endif()

set(ENV{LVRS_INSTALL_PREFIX} "/custom-env-prefix")
include("${LVRS_SOURCE_DIR}/cmake/LVRSInstallDefaults.cmake")
if(NOT CMAKE_INSTALL_PREFIX STREQUAL "/custom-env-prefix")
    message(FATAL_ERROR "LVRS_INSTALL_PREFIX override was ignored.")
endif()

set(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT FALSE)
set(CMAKE_INSTALL_PREFIX "/explicit-cmake-prefix")
include("${LVRS_SOURCE_DIR}/cmake/LVRSInstallDefaults.cmake")
if(NOT CMAKE_INSTALL_PREFIX STREQUAL "/explicit-cmake-prefix")
    message(FATAL_ERROR "Explicit CMake prefix was overwritten.")
endif()

unset(ENV{HOME})
unset(ENV{LVRS_INSTALL_PREFIX})
set(ENV{USERPROFILE} "/windows-test-home")
unset(CMAKE_INSTALL_PREFIX)
set(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT TRUE)
include("${LVRS_SOURCE_DIR}/cmake/LVRSInstallDefaults.cmake")
if(NOT CMAKE_INSTALL_PREFIX STREQUAL "/windows-test-home/.local/SDK/LVRS")
    message(FATAL_ERROR "Windows default install prefix must be inside the SDK directory.")
endif()
